-- Tabla de Cursos
CREATE TABLE CURSO (
    ID_CURSO NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    CREDITOS NUMBER NOT NULL,
    ESTADO NUMBER(1) CHECK (ESTADO IN (0, 1)), -- 0 = Inactivo, 1 = Activo
    CUPOS NUMBER NOT NULL
);

-- Tabla de Horarios
CREATE TABLE HORARIO (
    ID_HORARIO NUMBER PRIMARY KEY,
    HORARIO VARCHAR2(2) NOT NULL -- Seguir un formato en específico, por ejemplo: LN (Lunes Noche)
);

-- Relación Curso-Horario
CREATE TABLE CURSO_HORARIO (
    ID_CURSO NUMBER,
    ID_HORARIO NUMBER,
    PRIMARY KEY (ID_CURSO, ID_HORARIO),
    FOREIGN KEY (ID_CURSO) REFERENCES CURSO(ID_CURSO),
    FOREIGN KEY (ID_HORARIO) REFERENCES HORARIO(ID_HORARIO)
);

-- Tabla de Requisitos y Correquisitos combinada
CREATE TABLE CURSO_RELACIONADO (
    ID_RELACION NUMBER PRIMARY KEY,
    ID_CURSO NUMBER,
    ID_CURSO_RELACIONADO NUMBER, -- Curso relacionado
    TIPO_RELACION VARCHAR2(20) CHECK (TIPO_RELACION IN ('Requisito', 'Correquisito')),
    FOREIGN KEY (ID_CURSO) REFERENCES CURSO(ID_CURSO),
    FOREIGN KEY (ID_CURSO_RELACIONADO) REFERENCES CURSO(ID_CURSO)
);

-- Tabla de Usuarios (Estudiantes, Docentes, Administración)
CREATE TABLE USUARIO (
    ID_USUARIO NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(50) NOT NULL,
    PRIMER_APELLIDO VARCHAR2(50) NOT NULL,
    SEGUNDO_APELLIDO VARCHAR2(50),
    CORREO VARCHAR2(100) UNIQUE NOT NULL,
    TIPO_USUARIO VARCHAR2(20) CHECK (TIPO_USUARIO IN ('Estudiante', 'Docente', 'Administrativo', 'Decanato')),
    ESTADO NUMBER(1) CHECK (ESTADO IN (0, 1)) -- 0 = Inactivo, 1 = Activo
);

-- Tabla de Teléfonos
CREATE TABLE TELEFONO (
    ID_TELEFONO NUMBER PRIMARY KEY,
    CODIGO_PAIS VARCHAR2(10) NOT NULL,
    TELEFONO VARCHAR2(20) NOT NULL
);

-- Relación Usuario-Teléfono
CREATE TABLE USUARIO_TELEFONO (
    ID_USUARIO NUMBER,
    ID_TELEFONO NUMBER,
    PRIMARY KEY (ID_USUARIO, ID_TELEFONO),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY (ID_TELEFONO) REFERENCES TELEFONO(ID_TELEFONO)
);

-- Tabla de Horario Matriculado
CREATE TABLE HORARIO_MATRICULADO (
    ID_HORARIO_MATRICULADO NUMBER PRIMARY KEY,
    FECHA_MATRICULA DATE NOT NULL,
    ID_USUARIO NUMBER,
    ID_CURSO NUMBER,
    ID_HORARIO NUMBER,
    ESTADO NUMBER(1) CHECK (ESTADO IN (0, 1)), -- 0 = No aprobado, 1 = Aprobado
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY (ID_CURSO, ID_HORARIO) REFERENCES CURSO_HORARIO(ID_CURSO, ID_HORARIO)
);

-- Tabla de Plan de Estudios
CREATE TABLE PLAN_ESTUDIOS (
    ID_PLAN_ESTUDIOS NUMBER PRIMARY KEY,
    NOMBRE_CARRERA VARCHAR2(100) NOT NULL
);

-- Relación Curso-Plan de Estudios
CREATE TABLE CURSOS_PLAN (
    ID_CURSO NUMBER,
    ID_PLAN_ESTUDIOS NUMBER,
    PRIMARY KEY (ID_CURSO, ID_PLAN_ESTUDIOS),
    FOREIGN KEY (ID_CURSO) REFERENCES CURSO(ID_CURSO),
    FOREIGN KEY (ID_PLAN_ESTUDIOS) REFERENCES PLAN_ESTUDIOS(ID_PLAN_ESTUDIOS)
);

-- Tabla de Informes de Progreso
CREATE TABLE INFORME_PROGRESO (
    ID_INFORME NUMBER PRIMARY KEY,
    ID_USUARIO NUMBER,
    ID_CURSO NUMBER,
    OBSERVACIONES VARCHAR2(255),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY (ID_CURSO) REFERENCES CURSO(ID_CURSO)
);

-- Tabla de Asignaciones de Docentes a Cursos
CREATE TABLE ASIGNACION_DOCENTE (
    ID_ASIGNACION NUMBER PRIMARY KEY,
    ID_USUARIO NUMBER, -- El docente asignado
    ID_CURSO NUMBER,
    ID_HORARIO NUMBER,
    ESTADO NUMBER(1) CHECK (ESTADO IN (0, 1)), -- 0 = Inactivo, 1 = Activo
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY (ID_CURSO, ID_HORARIO) REFERENCES CURSO_HORARIO(ID_CURSO, ID_HORARIO)
);

-- Tabla de Aulas
CREATE TABLE AULAS (
    ID_AULA NUMBER PRIMARY KEY,
    NOMBRE_AULA VARCHAR2(50) UNIQUE NOT NULL,
    CAPACIDAD NUMBER NOT NULL,
    ESTADO NUMBER(1) CHECK (ESTADO IN (0, 1)) -- 0 = Inactivo, 1 = Activo
);

-- Relación Curso-Horario-Aula
CREATE TABLE CURSO_AULA (
    ID_CURSO NUMBER,
    ID_HORARIO NUMBER,
    ID_AULA NUMBER,
    PRIMARY KEY (ID_CURSO, ID_HORARIO, ID_AULA),
    FOREIGN KEY (ID_CURSO) REFERENCES CURSO(ID_CURSO),
    FOREIGN KEY (ID_HORARIO) REFERENCES HORARIO(ID_HORARIO),
    FOREIGN KEY (ID_AULA) REFERENCES AULAS(ID_AULA)
);

-- Tabla de Historial Académico
CREATE TABLE HISTORIAL_ACADEMICO (
    ID_HISTORIAL NUMBER PRIMARY KEY,
    ID_USUARIO NUMBER,
    ID_CURSO NUMBER,
    PERIODO VARCHAR2(50),
    ANO NUMBER,
    CALIFICACION NUMBER CHECK (CALIFICACION BETWEEN 0 AND 100),
    ESTADO NUMBER(1) CHECK (ESTADO IN (0, 1)), -- 0 = No aprobado, 1 = Aprobado
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY (ID_CURSO) REFERENCES CURSO(ID_CURSO)
);


-- Tabla de Notificaciones
CREATE TABLE NOTIFICACIONES (
    ID_NOTIFICACION NUMBER PRIMARY KEY,
    ID_USUARIO NUMBER,
    MENSAJE VARCHAR2(255),
    FECHA_ENVIO DATE,
    LEIDO NUMBER(1) CHECK (LEIDO IN (0, 1)), -- 0 = No leído, 1 = Leído
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

-- Tabla de Especialización de Docentes
CREATE TABLE ESPECIALIZACION_DOCENTE (
    ID_ESPECIALIZACION NUMBER PRIMARY KEY,
    ID_USUARIO NUMBER,
    AREA_ESPECIALIZACION VARCHAR2(100),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);
