/***********TRIGGER AUDITORIA CREADO/MODIFICADO POR*****************/

-- Trigger de auditor�a para FIDE_CURSO_TB
CREATE OR REPLACE TRIGGER FIDE_CURSO_TB_CREADO_MODIFICADO_POR
BEFORE INSERT OR UPDATE ON FIDE_CURSO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;
/

-- Trigger de auditor�a para FIDE_CURSO_HORARIO_TB
CREATE OR REPLACE TRIGGER FIDE_CURSO_HORARIO_TB_CREADO_MODIFICADO_POR
BEFORE INSERT OR UPDATE ON FIDE_CURSO_HORARIO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;
/


-- Trigger de auditor�a para FIDE_HORARIO_TB
CREATE OR REPLACE TRIGGER FIDE_HORARIO_TB_CREADO_MODIFICADO_POR
BEFORE INSERT OR UPDATE ON FIDE_HORARIO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;
/

-- Trigger de auditor�a para FIDE_CURSO_RELACIONADO_TB
CREATE OR REPLACE TRIGGER FIDE_CURSO_RELACIONADO_TB_CREADO_MODIFICADO_POR
BEFORE INSERT OR UPDATE ON FIDE_CURSO_RELACIONADO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;
/

-- Trigger de auditor�a para FIDE_USUARIO_TB
CREATE OR REPLACE TRIGGER FIDE_USUARIO_TB_CREADO_MODIFICADO_POR
BEFORE INSERT OR UPDATE ON FIDE_USUARIO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;
/

-- Trigger de auditor�a para FIDE_DIRECCION_TB
CREATE OR REPLACE TRIGGER FIDE_DIRECCION_TB_CREADO_MODIFICADO_POR
BEFORE INSERT OR UPDATE ON FIDE_DIRECCION_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;
/

-- Trigger de auditor�a para FIDE_PAIS_TB
CREATE OR REPLACE TRIGGER FIDE_PAIS_TB_CREADO_MODIFICADO_POR
BEFORE INSERT OR UPDATE ON FIDE_PAIS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;
/

-- Trigger de auditor�a para FIDE_PROVINCIA_TB
CREATE OR REPLACE TRIGGER FIDE_PROVINCIA_TB_CREADO_MODIFICADO_POR
BEFORE INSERT OR UPDATE ON FIDE_PROVINCIA_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;
/

-- Trigger de auditor�a para FIDE_CANTON_TB
CREATE OR REPLACE TRIGGER FIDE_CANTON_TB_CREADO_MODIFICADO_POR
BEFORE INSERT OR UPDATE ON FIDE_CANTON_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;
/

-- Trigger de auditor�a para FIDE_DISTRITO_TB
CREATE OR REPLACE TRIGGER FIDE_DISTRITO_TB_CREADO_MODIFICADO_POR
BEFORE INSERT OR UPDATE ON FIDE_DISTRITO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;
/

-- Trigger de auditor�a para FIDE_HORARIO_MATRICULADO_TB
CREATE OR REPLACE TRIGGER FIDE_HORARIO_MATRICULADO_TB_CREADO_MODIFICADO_POR
BEFORE INSERT OR UPDATE ON FIDE_HORARIO_MATRICULADO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;
/

-- Trigger de auditor�a para FIDE_PLAN_ESTUDIOS_TB
CREATE OR REPLACE TRIGGER FIDE_PLAN_ESTUDIOS_TB_CREADO_MODIFICADO_POR
BEFORE INSERT OR UPDATE ON FIDE_PLAN_ESTUDIOS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;
/

-- Trigger de auditor�a para FIDE_CURSOS_PLAN_TB
CREATE OR REPLACE TRIGGER FIDE_CURSOS_PLAN_TB_CREADO_MODIFICADO_POR
BEFORE INSERT OR UPDATE ON FIDE_CURSOS_PLAN_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;
/

-- Trigger de auditor�a para FIDE_ASIGNACION_DOCENTE_TB
CREATE OR REPLACE TRIGGER FIDE_ASIGNACION_DOCENTE_TB_CREADO_MODIFICADO_POR
BEFORE INSERT OR UPDATE ON FIDE_ASIGNACION_DOCENTE_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;
/

-- Trigger de auditor�a para FIDE_AULAS_TB
CREATE OR REPLACE TRIGGER FIDE_AULAS_TB_CREADO_MODIFICADO_POR
BEFORE INSERT OR UPDATE ON FIDE_AULAS_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;
/

-- Trigger de auditor�a para FIDE_CURSO_AULA_TB
CREATE OR REPLACE TRIGGER FIDE_CURSO_AULA_TB_CREADO_MODIFICADO_POR
BEFORE INSERT OR UPDATE ON FIDE_CURSO_AULA_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;
/

-- Trigger de auditor�a para FIDE_HISTORIAL_ACADEMICO_TB
CREATE OR REPLACE TRIGGER FIDE_HISTORIAL_ACADEMICO_TB_CREADO_MODIFICADO_POR
BEFORE INSERT OR UPDATE ON FIDE_HISTORIAL_ACADEMICO_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;
/

-- Trigger de auditor�a para FIDE_NOTIFICACIONES_TB
CREATE OR REPLACE TRIGGER FIDE_NOTIFICACIONES_TB_CREADO_MODIFICADO_POR
BEFORE INSERT OR UPDATE ON FIDE_NOTIFICACIONES_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;
/

-- Trigger de auditor�a para FIDE_ESPECIALIZACION_DOCENTE_TB
CREATE OR REPLACE TRIGGER FIDE_ESPECIALIZACION_DOCENTE_TB_CREADO_MODIFICADO_POR
BEFORE INSERT OR UPDATE ON FIDE_ESPECIALIZACION_DOCENTE_TB
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER;
    ELSE
        :NEW.MODIFICADO_POR := USER;
    END IF;
END;