--- CREAR CURSO ---
CREATE OR REPLACE PROCEDURE FIDE_CURSO_TB_INSERTAR_CURSO_SP (
    P_NOMBRE IN VARCHAR2,
    P_CREDITOS IN NUMBER,
    P_CUPOS IN NUMBER,
    P_ID_ESTADO IN NUMBER,
    P_ID_CURSO OUT NUMBER
) 
IS
BEGIN
    -- Llamar a la función para insertar el curso
    P_ID_CURSO := FIDE_INSERTAR_CURSO(P_NOMBRE, P_CREDITOS, P_CUPOS, P_ID_ESTADO);
    
    -- Puedes agregar aquí cualquier otro proceso que desees hacer, como registros adicionales o actualizaciones
END;
/
--- ACTUALIZAR CURSO ---
CREATE OR REPLACE PROCEDURE FIDE_CURSO_TB_EDITAR_CURSO_SP (
    P_ID_CURSO IN NUMBER,
    P_NOMBRE IN VARCHAR2,
    P_CREDITOS IN NUMBER,
    P_CUPOS IN NUMBER,
    P_RESULTADO OUT VARCHAR2
) 
IS
BEGIN
    -- Llamar a la función para editar el curso
    P_RESULTADO := FIDE_EDITAR_CURSO(P_ID_CURSO, P_NOMBRE, P_CREDITOS, P_CUPOS);
END;
/
--- CAMBIAR ESTADO CURSOS ---
CREATE OR REPLACE PROCEDURE FIDE_CURSO_TB_CAMBIAR_ESTADO_CURSO_SP (
    P_ID_CURSO IN NUMBER,
    P_RESULTADO OUT VARCHAR2
) 
IS
BEGIN
    -- Llamar a la función para cambiar el estado del curso a 0
    P_RESULTADO := FIDE_CAMBIAR_ESTADO_CURSOS(P_ID_CURSO);
END;

/
--- REGISTRAR DOCENTE ---
CREATE OR REPLACE PROCEDURE FIDE_USUARIO_TB_REGISTRAR_DOCENTE_SP (
    P_NOMBRE IN VARCHAR2,
    P_PRIMER_APELLIDO IN VARCHAR2,
    P_SEGUNDO_APELLIDO IN VARCHAR2,
    P_CORREO IN VARCHAR2,
    P_TIPO_USUARIO IN VARCHAR2,
    P_CODIGO_PAIS IN VARCHAR2,
    P_TELEFONO IN VARCHAR2,
    P_ID_DIRECCION IN NUMBER,
    P_ID_ESPECIALIZACION IN NUMBER,
    P_ID_USUARIO OUT NUMBER
) 
IS
BEGIN
    -- Llamar a la función para registrar el docente
    P_ID_USUARIO := FIDE_REGISTRAR_DOCENTE(P_NOMBRE, P_PRIMER_APELLIDO, P_SEGUNDO_APELLIDO, 
                                            P_CORREO, P_TIPO_USUARIO, P_CODIGO_PAIS, 
                                            P_TELEFONO, P_ID_DIRECCION, P_ID_ESPECIALIZACION);
END;
/
--- EDITAR DOCENTE ---
CREATE OR REPLACE PROCEDURE FIDE_USUARIO_TB_EDITAR_DOCENTE_SP (
    P_ID_USUARIO IN NUMBER,
    P_NOMBRE IN VARCHAR2,
    P_PRIMER_APELLIDO IN VARCHAR2,
    P_SEGUNDO_APELLIDO IN VARCHAR2,
    P_CORREO IN VARCHAR2,
    P_TIPO_USUARIO IN VARCHAR2,
    P_CODIGO_PAIS IN VARCHAR2,
    P_TELEFONO IN VARCHAR2,
    P_ID_DIRECCION IN NUMBER,
    P_ID_ESPECIALIZACION IN NUMBER,
    P_RESULTADO OUT VARCHAR2
) 
IS
BEGIN
    -- Llamar a la función para editar el docente
    P_RESULTADO := FIDE_EDITAR_DOCENTE(P_ID_USUARIO, P_NOMBRE, P_PRIMER_APELLIDO, 
                                       P_SEGUNDO_APELLIDO, P_CORREO, P_TIPO_USUARIO, 
                                       P_CODIGO_PAIS, P_TELEFONO, P_ID_DIRECCION, 
                                       P_ID_ESPECIALIZACION);
END;

/

--- AGREGAR AULA ---
CREATE OR REPLACE PROCEDURE FIDE_AULAS_TB_AGREGAR_AULA_SP (
    P_NOMBRE_AULA IN VARCHAR2,
    P_CAPACIDAD IN NUMBER,
    P_ID_ESTADO IN NUMBER,
    P_ID_AULA OUT NUMBER
) 
IS
BEGIN
    -- Llamar a la función para agregar el aula
    P_ID_AULA := FIDE_AULAS_TB_AGREGAR_FN(P_NOMBRE_AULA, P_CAPACIDAD, P_ID_ESTADO);
END;

/
--- AGREGAR UN NUEVO HORARIO ---
CREATE OR REPLACE PROCEDURE FIDE_HORARIO_TB_AGREGAR_HORARIO_SP (
    P_DIA_SEMANA IN VARCHAR2,
    P_TURNO IN VARCHAR2,
    P_ID_ESTADO IN NUMBER,
    P_ID_HORARIO OUT NUMBER
) 
IS
BEGIN
    -- Llamar a la función para agregar el horario
    P_ID_HORARIO := FIDE_HORARIO_TB_AGREGAR_FN(P_DIA_SEMANA, P_TURNO, P_ID_ESTADO);
END;

/
--- EDITAR HORARIO ---
CREATE OR REPLACE PROCEDURE FIDE_HORARIO_TB_EDITAR_HORARIO_SP(
    P_ID_HORARIO IN NUMBER,
    P_DIA_SEMANA IN VARCHAR2,
    P_TURNO IN VARCHAR2,
    P_ID_ESTADO IN NUMBER,
    P_RESULTADO OUT VARCHAR2
) 
IS
BEGIN
    -- Llamar a la función para editar el horario
    P_RESULTADO := FIDE_HORARIO_TB_EDITAR_FN(P_ID_HORARIO, P_DIA_SEMANA, P_TURNO, P_ID_ESTADO);
END;
/