/************SECUENCIAS Y TRIGGERS PARA PK***************/
-- Secuencia y Trigger para FIDE_ESTADO_TB
CREATE SEQUENCE FIDE_ESTADO_ID_ESTADO_SEQ
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER FIDE_ESTADO_SECUENCIA_TRG
BEFORE INSERT ON FIDE_ESTADO_TB
FOR EACH ROW
BEGIN
    :NEW.ID_ESTADO := FIDE_ESTADO_ID_ESTADO_SEQ.NEXTVAL;
END;
/

-- Secuencia y Trigger para FIDE_CURSO_TB
CREATE SEQUENCE FIDE_CURSO_ID_CURSO_SEQ
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER FIDE_CURSO_SECUENCIA_TRG
BEFORE INSERT ON FIDE_CURSO_TB
FOR EACH ROW
BEGIN
    :NEW.ID_CURSO := FIDE_CURSO_ID_CURSO_SEQ.NEXTVAL;
END;
/

-- Secuencia y Trigger para FIDE_HORARIO_TB
CREATE SEQUENCE FIDE_HORARIO_ID_HORARIO_SEQ
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER FIDE_HORARIO_SECUENCIA_TRG
BEFORE INSERT ON FIDE_HORARIO_TB
FOR EACH ROW
BEGIN
    :NEW.ID_HORARIO := FIDE_HORARIO_ID_HORARIO_SEQ.NEXTVAL;
END;
/

-- Secuencia y Trigger para FIDE_CURSO_RELACIONADO_TB
CREATE SEQUENCE FIDE_CURSO_RELACIONADO_ID_REQUISITO_SEQ
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER FIDE_CURSO_RELACIONADO_SECUENCIA_TRG
BEFORE INSERT ON FIDE_CURSO_RELACIONADO_TB
FOR EACH ROW
BEGIN
    :NEW.ID_REQUISITO := FIDE_CURSO_RELACIONADO_ID_REQUISITO_SEQ.NEXTVAL;
END;
/

-- Secuencia y Trigger para FIDE_USUARIO_TB
CREATE SEQUENCE FIDE_USUARIO_ID_USUARIO_SEQ
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER FIDE_USUARIO_SECUENCIA_TRG
BEFORE INSERT ON FIDE_USUARIO_TB
FOR EACH ROW
BEGIN
    :NEW.ID_USUARIO := FIDE_USUARIO_ID_USUARIO_SEQ.NEXTVAL;
END;
/

-- Secuencia y Trigger para FIDE_DIRECCION_TB
CREATE SEQUENCE FIDE_DIRECCION_ID_DIRECCION_SEQ
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER FIDE_DIRECCION_SECUENCIA_TRG
BEFORE INSERT ON FIDE_DIRECCION_TB
FOR EACH ROW
BEGIN
    :NEW.ID_DIRECCION := FIDE_DIRECCION_ID_DIRECCION_SEQ.NEXTVAL;
END;
/

-- Secuencia y Trigger para FIDE_PAIS_TB
CREATE SEQUENCE FIDE_PAIS_ID_PAIS_SEQ
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER FIDE_PAIS_SECUENCIA_TRG
BEFORE INSERT ON FIDE_PAIS_TB
FOR EACH ROW
BEGIN
    :NEW.ID_PAIS := FIDE_PAIS_ID_PAIS_SEQ.NEXTVAL;
END;
/

-- Secuencia y Trigger para FIDE_PROVINCIA_TB
CREATE SEQUENCE FIDE_PROVINCIA_ID_PROVINCIA_SEQ
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER FIDE_PROVINCIA_SECUENCIA_TRG
BEFORE INSERT ON FIDE_PROVINCIA_TB
FOR EACH ROW
BEGIN
    :NEW.ID_PROVINCIA := FIDE_PROVINCIA_ID_PROVINCIA_SEQ.NEXTVAL;
END;
/

-- Secuencia y Trigger para FIDE_CANTON_TB
CREATE SEQUENCE FIDE_CANTON_ID_CANTON_SEQ
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER FIDE_CANTON_SECUENCIA_TRG
BEFORE INSERT ON FIDE_CANTON_TB
FOR EACH ROW
BEGIN
    :NEW.ID_CANTON := FIDE_CANTON_ID_CANTON_SEQ.NEXTVAL;
END;
/

-- Secuencia y Trigger para FIDE_DISTRITO_TB
CREATE SEQUENCE FIDE_DISTRITO_ID_DISTRITO_SEQ
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER FIDE_DISTRITO_SECUENCIA_TRG
BEFORE INSERT ON FIDE_DISTRITO_TB
FOR EACH ROW
BEGIN
    :NEW.ID_DISTRITO := FIDE_DISTRITO_ID_DISTRITO_SEQ.NEXTVAL;
END;
/

-- Secuencia y Trigger para FIDE_HORARIO_MATRICULADO_TB
CREATE SEQUENCE FIDE_HORARIO_MATRICULADO_ID_HORARIO_MATRICULADO_SEQ
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER FIDE_HORARIO_MATRICULADO_SECUENCIA_TRG
BEFORE INSERT ON FIDE_HORARIO_MATRICULADO_TB
FOR EACH ROW
BEGIN
    :NEW.ID_HORARIO_MATRICULADO := FIDE_HORARIO_MATRICULADO_ID_HORARIO_MATRICULADO_SEQ.NEXTVAL;
END;
/

-- Secuencia y Trigger para FIDE_PLAN_ESTUDIOS_TB
CREATE SEQUENCE FIDE_PLAN_ESTUDIOS_ID_PLAN_ESTUDIOS_SEQ
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER FIDE_PLAN_ESTUDIOS_SECUENCIA_TRG
BEFORE INSERT ON FIDE_PLAN_ESTUDIOS_TB
FOR EACH ROW
BEGIN
    :NEW.ID_PLAN_ESTUDIOS := FIDE_PLAN_ESTUDIOS_ID_PLAN_ESTUDIOS_SEQ.NEXTVAL;
END;
/

-- Secuencia y Trigger para FIDE_HORARIO_MATRICULADO_TB
CREATE SEQUENCE FIDE_HORARIO_MATRICULADO_ID_SEQ
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER FIDE_HORARIO_MATRICULADO_SECUENCIA_TRG
BEFORE INSERT ON FIDE_HORARIO_MATRICULADO_TB
FOR EACH ROW
BEGIN
    :NEW.ID_HORARIO_MATRICULADO := FIDE_HORARIO_MATRICULADO_ID_SEQ.NEXTVAL;
END;
/



-- Secuencia y Trigger para FIDE_ASIGNACION_DOCENTE_TB
CREATE SEQUENCE FIDE_ASIGNACION_DOCENTE_ID_ASIGNACION_SEQ
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER FIDE_ASIGNACION_DOCENTE_SECUENCIA_TRG
BEFORE INSERT ON FIDE_ASIGNACION_DOCENTE_TB
FOR EACH ROW
BEGIN
    :NEW.ID_ASIGNACION := FIDE_ASIGNACION_DOCENTE_ID_ASIGNACION_SEQ.NEXTVAL;
END;
/

-- Secuencia y Trigger para FIDE_AULAS_TB
CREATE SEQUENCE FIDE_AULAS_ID_AULA_SEQ
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER FIDE_AULAS_SECUENCIA_TRG
BEFORE INSERT ON FIDE_AULAS_TB
FOR EACH ROW
BEGIN
    :NEW.ID_AULA := FIDE_AULAS_ID_AULA_SEQ.NEXTVAL;
END;
/

-- Secuencia y Trigger para FIDE_CURSO_AULA_TB
CREATE SEQUENCE FIDE_CURSO_AULA_SEQ
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER FIDE_CURSO_AULA_SECUENCIA_TRG
BEFORE INSERT ON FIDE_CURSO_AULA_TB
FOR EACH ROW
BEGIN
    :NEW.ID_CURSO := FIDE_CURSO_AULA_SEQ.NEXTVAL;
END;
/

-- Secuencia y Trigger para FIDE_HISTORIAL_ACADEMICO_TB
CREATE SEQUENCE FIDE_HISTORIAL_ACADEMICO_ID_HISTORIAL_SEQ
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER FIDE_HISTORIAL_ACADEMICO_SECUENCIA_TRG
BEFORE INSERT ON FIDE_HISTORIAL_ACADEMICO_TB
FOR EACH ROW
BEGIN
    :NEW.ID_HISTORIAL := FIDE_HISTORIAL_ACADEMICO_ID_HISTORIAL_SEQ.NEXTVAL;
END;
/

-- Secuencia y Trigger para FIDE_NOTIFICACIONES_TB
CREATE SEQUENCE FIDE_NOTIFICACIONES_ID_NOTIFICACION_SEQ
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER FIDE_NOTIFICACIONES_SECUENCIA_TRG
BEFORE INSERT ON FIDE_NOTIFICACIONES_TB
FOR EACH ROW
BEGIN
    :NEW.ID_NOTIFICACION := FIDE_NOTIFICACIONES_ID_NOTIFICACION_SEQ.NEXTVAL;
END;
/

-- Secuencia y Trigger para FIDE_ESPECIALIZACION_DOCENTE_TB
CREATE SEQUENCE FIDE_ESPECIALIZACION_DOCENTE_ID_ESPECIALIZACION_SEQ
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER FIDE_ESPECIALIZACION_DOCENTE_SECUENCIA_TRG
BEFORE INSERT ON FIDE_ESPECIALIZACION_DOCENTE_TB
FOR EACH ROW
BEGIN
    :NEW.ID_ESPECIALIZACION := FIDE_ESPECIALIZACION_DOCENTE_ID_ESPECIALIZACION_SEQ.NEXTVAL;
END;
/
